<?php
/*
* Copyright 2018 Baidu, Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License"); you may not
* use this file except in compliance with the License. You may obtain a copy of
* the License at
*
* Http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
* WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
* License for the specific language governing permissions and limitations under
* the License.
*/


namespace BaiduBce\Services\PeerConn;

use BaiduBce\Auth\BceV1Signer;
use BaiduBce\BceBaseClient;
use BaiduBce\Http\BceHttpClient;
use BaiduBce\Http\HttpHeaders;
use BaiduBce\Http\HttpMethod;
use BaiduBce\Http\HttpContentTypes;
use BaiduBce\Services\PeerConn\model\Billing;

/**
 * This module provides a client class for PeerConnClient.
 */
class PeerConnClient extends BceBaseClient
{

    private $signer;
    private $httpClient;
    private $prefix = '/v1';

    /**
     * The PeerConnClient constructor.
     *
     * @param array $config The client configuration
     */
    function __construct(array $config)
    {
        parent::__construct($config, 'peerconn');
        $this->signer = new BceV1Signer();
        $this->httpClient = new BceHttpClient();
    }

    /**
     * Create an PeerConn with the specified options.
     *
     * @param int $bandwidthInMbps
     *          specify the bandwidth in Mbps.
     *
     * @param String $description
     *          specify the description of the PeerConn.The optional parameter
     *
     * @param string $localIfName
     *          the name of local interface of PeerConn. The optional parameter
     *
     * @param string $localVpcId
     *          the id of local vpc of PeerConn.
     *
     * @param string $peerAccountId
     *          the id of peer account of PeerConn.if it is the same account, this parameter does not need to be passed.
     *
     * @param string $peerVpcId
     *          the id of peer vpc of PeerConn.
     *
     * @param string $peerRegion
     *          the peer region name of PeerConn.
     *
     * @param string $peerIfName
     *          the peer interface name of PeerConn. The optional parameter.only same account can set.
     *
     * @param Billing $billing
     *          billing information. The optional parameter, default paymentTiming is Postpaid
     *
     * @param string $clientToken
     *          if the clientToken is not specified by the user, a random String
     *          generated by default algorithm will be used.
     *
     * @param array $options
     *          The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating PeerConnClient instance.
     *
     * @return the id of the PeerConn
     */
    public function createPeerConn($bandwidthInMbps, $localVpcId, $peerVpcId, $peerRegion, $billing, $peerAccountId = null, $peerIfName = null, $description = null, $localIfName = null, $clientToken = null, $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        $body = array();
        if (empty($bandwidthInMbps)) {
            throw new \InvalidArgumentException(
                'request $bandwidthInMbps  should not be empty .'
            );
        }
        if (empty($localVpcId)) {
            throw new \InvalidArgumentException(
                'request $localVpcId  should not be empty .'
            );
        }
        if (empty($peerVpcId)) {
            throw new \InvalidArgumentException(
                'request $peerVpcId  should not be empty .'
            );
        }
        if (empty($peerRegion)) {
            throw new \InvalidArgumentException(
                'request $peerRegion  should not be empty .'
            );
        }
        if (empty($billing)) {
            throw new \InvalidArgumentException(
                'request $billing  should not be empty .'
            );
        }
        $body['bandwidthInMbps'] = $bandwidthInMbps;
        $body['localVpcId'] = $localVpcId;
        $body['peerVpcId'] = $peerVpcId;
        $body['peerRegion'] = $peerRegion;
        $body['billing'] = $this->objectToArray($billing);
        $body['description'] = $description;
        $body['localIfName'] = $localIfName;
        $body['peerIfName'] = $peerIfName;
        $body['peerAccountId'] = $peerAccountId;
        $params = array();
        if (empty($clientToken)) {
            $params['clientToken'] = $this->generateClientToken();
        } else {
            $params['clientToken'] = $clientToken;
        }

        return $this->sendRequest(
            HttpMethod::POST,
            array(
                'config' => $config,
                'params' => $params,
                'body' => json_encode($body),
            ),
            '/peerconn'
        );
    }

    /**
     * Resizing PeerConn
     *
     * @param string peerConnId
     *          PeerConn's id to be resized
     *
     * @param int newBandwidthInMbps
     *          specify new bandwidth in Mbps for PeerConn
     *
     * @param string $clientToken
     *          if the clientToken is not specified by the user, a random String
     *          generated by default algorithm will be used.
     *
     * @param array $options
     *          The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating PeerConnClient instance.
     *
     * @return mixed
     */
    public function resizePeerConn($peerConnId, $newBandwidthInMbps, $clientToken = null, $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        $body = array();
        if (empty($clientToken)) {
            $params['clientToken'] = $this->generateClientToken();
        } else {
            $params['clientToken'] = $clientToken;
        }
        if (empty($peerConnId)) {
            throw new \InvalidArgumentException(
                'request $peerConnId  should not be empty .'
            );
        }
        if (empty($newBandwidthInMbps)) {
            throw new \InvalidArgumentException(
                'request $newBandwidthInMbps  should not be empty .'
            );
        }
        $body['newBandwidthInMbps'] = $newBandwidthInMbps;
        $params = array();
        $params['resize'] = null;

        return $this->sendRequest(
            HttpMethod::PUT,
            array(
                'config' => $config,
                'params' => $params,
                'body' => json_encode($body),
            ),
            '/peerconn/' . $peerConnId
        );
    }

    /**
     * update PeerConn
     *
     * @param string $peerConnId
     *          PeerConn's id to be updated
     *
     * @param string $localIfId
     *           PeerConn's local interface id to be updated
     *
     * @param string $localIfName
     *          specify the new localIfName for PeerConn.
     *
     * @param string $description
     *          specify the new description for PeerConn.
     *
     * @param string $clientToken
     *          if the clientToken is not specified by the user, a random String
     *          generated by default algorithm will be used.
     *
     * @param array $options
     *          The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating PeerConnClient instance.
     *
     * @return mixed
     */
    public function updatePeerConn($peerConnId, $localIfId, $localIfName = null, $description = null, $clientToken = null, $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        $params = array();
        $body = array();
        if (empty($clientToken)) {
            $params['clientToken'] = $this->generateClientToken();
        } else {
            $params['clientToken'] = $clientToken;
        }
        if (empty($peerConnId)) {
            throw new \InvalidArgumentException(
                'request $peerConnId  should not be empty .'
            );
        }
        if (empty($localIfId)) {
            throw new \InvalidArgumentException(
                'request $localIfId  should not be empty .'
            );
        }
        $body['localIfId'] = $localIfId;
        $body['localIfName'] = $localIfName;
        $body['description'] = $description;

        return $this->sendRequest(
            HttpMethod::PUT,
            array(
                'config' => $config,
                'body' => json_encode($body),
                'params' => $params,
            ),
            '/peerconn/' . $peerConnId
        );
    }

    /**
     * PurchaseReserved PeerConn with fixed duration.only initiator can PurchaseReserved for diff account.
     *
     * @param string $peerConnId
     *          PeerConn's id to be renewed
     *
     * @param Billing $billing
     *          billing information.
     *
     * @param string $clientToken
     *          if the clientToken is not specified by the user, a random String
     *          generated by default algorithm will be used.
     *
     * @param array $options
     *          The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating PeerConnClient instance.
     *
     * @return mixed
     */
    public function purchaseReservedPeerConn($peerConnId, $billing, $clientToken = null, $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        $body = array();
        if (empty($peerConnId)) {
            throw new \InvalidArgumentException(
                'request $peerConnId  should not be empty .'
            );
        }
        if (empty($billing)) {
            throw new \InvalidArgumentException(
                'request $billing  should not be empty .'
            );
        } else {
            $reservation = array();
            $reservation['reservationTimeUnit'] = $billing->reservation->reservationTimeUnit;
            $reservation['reservationLength'] = $billing->reservation->reservationLength;
            $billingBody = array();
            $billingBody['reservation'] = $reservation;
            $body['billing'] = $billingBody;
        }
        $params = array();
        if (empty($clientToken)) {
            $clientToken = $this->generateClientToken();
        }
        $params['purchaseReserved'] = null;
        $params['clientToken'] = $clientToken;

        return $this->sendRequest(
            HttpMethod::PUT,
            array(
                'config' => $config,
                'params' => $params,
                'body' => json_encode($body),
            ),
            '/peerconn/' . $peerConnId
        );
    }


    /**
     * get a list of PeerConn which belong to the specified vpc .
     *
     * @param string $vpcId
     *          vpc's id condition
     *
     *
     * @param string $marker
     *          The optional parameter marker specified in the original request to specify
     *          where in the results to begin listing.
     *
     * @param int $maxKeys
     *          The optional parameter to specifies the max number of list result to return.
     *          The default value is 1000.
     *
     * @param array $options
     *           The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating PeerConnClient instance.
     *
     * @return a list of PeerConn
     */
    public function listPeerConns($vpcId, $marker = null, $maxKeys = 1000, $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        $params = array();
        if ($vpcId !== null) {
            $params['vpcId'] = $vpcId;
        }
        if ($marker !== null) {
            $params['marker'] = $marker;
        }
        if ($maxKeys !== null) {
            $params['maxKeys'] = $maxKeys;
        }

        return $this->sendRequest(
            HttpMethod::GET,
            array(
                'config' => $config,
                'params' => $params,
            ),
            '/peerconn'
        );
    }

    /**
     * get a detail of the PeerConn which you specified .
     *
     * @param string $peerConnId
     *         PeerConn's id condition
     *
     * @param array $options
     *           The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating PeerConnClient instance.
     *
     * @return the detail of PeerConn which you specified
     */
    public function getPeerConn($peerConnId, $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        $params = array();
        if (empty($peerConnId)) {
            throw new \InvalidArgumentException(
                'request $peerConnId  should not be empty .'
            );
        }
        return $this->sendRequest(
            HttpMethod::GET,
            array(
                'config' => $config,
                'params' => $params,
            ),
            '/peerconn/' . $peerConnId
        );
    }


    /**
     * release the PeerConn(delete operation)
     * Only the Postpaid instance or Prepaid which is expired can be released.
     *
     * @param string $peerConnId
     *          the id of PeerConn which to be released
     *
     * @param string $clientToken
     *          if the clientToken is not specified by the user, a random String
     *          generated by default algorithm will be used.
     *
     * @param array $options
     *          The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating EipClient instance.
     *
     * @return mixed
     */
    public function releasePeerConn($peerConnId, $clientToken = null, $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        if (empty($peerConnId)) {
            throw new \InvalidArgumentException(
                'request $peerConnId  should not be empty .'
            );
        }
        if (empty($clientToken)) {
            $clientToken = $this->generateClientToken();
        }
        $params = array();
        $params['clientToken'] = $clientToken;

        return $this->sendRequest(
            HttpMethod::DELETE,
            array(
                'config' => $config,
                'params' => $params,
            ),
            '/peerconn/' . $peerConnId
        );
    }

    /**
     * accept the apply of PeerConn
     *
     * @param string $peerConnId
     *          the id of PeerConn which to be deal apply.
     *
     *
     * @param string $clientToken
     *          if the clientToken is not specified by the user, a random String
     *          generated by default algorithm will be used.
     *
     * @param array $options
     *          The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating EipClient instance.
     *
     * @return mixed
     */
    public function acceptPeerConnApply($peerConnId, $clientToken = null, $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        $params = array();
        $body = array();
        if (empty($clientToken)) {
            $params['clientToken'] = $this->generateClientToken();
        } else {
            $params['clientToken'] = $clientToken;
        }
        if (empty($peerConnId)) {
            throw new \InvalidArgumentException(
                'request $peerConnId  should not be empty .'
            );
        }
        $params['accept'] = null;

        return $this->sendRequest(
            HttpMethod::PUT,
            array(
                'config' => $config,
                'params' => $params,
            ),
            '/peerconn/' . $peerConnId
        );
    }

    /**
     * reject the apply of PeerConn
     *
     * @param string $peerConnId
     *          the id of PeerConn which to be deal apply.
     *
     *
     * @param string $clientToken
     *          if the clientToken is not specified by the user, a random String
     *          generated by default algorithm will be used.
     *
     * @param array $options
     *          The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating EipClient instance.
     *
     * @return mixed
     */
    public function rejectPeerConnApply($peerConnId, $clientToken = null, $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        $params = array();
        $body = array();
        if (empty($clientToken)) {
            $params['clientToken'] = $this->generateClientToken();
        } else {
            $params['clientToken'] = $clientToken;
        }
        if (empty($peerConnId)) {
            throw new \InvalidArgumentException(
                'request $peerConnId  should not be empty .'
            );
        }
        $params['reject'] = null;

        return $this->sendRequest(
            HttpMethod::PUT,
            array(
                'config' => $config,
                'params' => $params,
            ),
            '/peerconn/' . $peerConnId
        );
    }


    /**
     * open PeerConn sync Dns record
     *
     * @param string $peerConnId
     *          the id of PeerConn which to be deal apply.
     *
     *
     * @param string role
     *          the param is "initiator" or "acceptor".
     *
     * @param string $clientToken
     *          if the clientToken is not specified by the user, a random String
     *          generated by default algorithm will be used.
     *
     * @param array $options
     *          The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating EipClient instance.
     *
     * @return mixed
     */
    public function openPeerConnSyncDns($peerConnId, $role, $clientToken = null, $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        $params = array();
        if (empty($clientToken)) {
            $params['clientToken'] = $this->generateClientToken();
        } else {
            $params['clientToken'] = $clientToken;
        }
        if (empty($peerConnId)) {
            throw new \InvalidArgumentException(
                'request $peerConnId  should not be empty .'
            );
        }
        if (empty($role)) {
            throw new \InvalidArgumentException(
                'request $role  should not be empty .'
            );
        } else {
            $params['role'] = $role;
        }
        $params['open'] = null;

        return $this->sendRequest(
            HttpMethod::PUT,
            array(
                'config' => $config,
                'params' => $params,
            ),
            '/peerconn/' . $peerConnId
        );
    }


    /**
     * close PeerConn sync Dns record
     *
     * @param string $peerConnId
     *          the id of PeerConn which to be deal apply.
     *
     *
     * @param string role
     *          the param is "initiator" or "acceptor".
     *
     * @param string $clientToken
     *          if the clientToken is not specified by the user, a random String
     *          generated by default algorithm will be used.
     *
     * @param array $options
     *          The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating EipClient instance.
     *
     * @return mixed
     */
    public function closePeerConnSyncDns($peerConnId, $role, $clientToken = null, $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        $params = array();
        if (empty($clientToken)) {
            $params['clientToken'] = $this->generateClientToken();
        } else {
            $params['clientToken'] = $clientToken;
        }
        if (empty($peerConnId)) {
            throw new \InvalidArgumentException(
                'request $peerConnId  should not be empty .'
            );
        }
        if (empty($role)) {
            throw new \InvalidArgumentException(
                'request $role  should not be empty .'
            );
        } else {
            $params['role'] = $role;
        }
        $params['close'] = null;

        return $this->sendRequest(
            HttpMethod::PUT,
            array(
                'config' => $config,
                'params' => $params,
            ),
            '/peerconn/' . $peerConnId
        );
    }

    /**
     * convert object to array
     *
     * @param object $obj
     *
     * @return array
     */
    function objectToArray($obj)
    {
        if (is_array($obj)) {
            return $obj;
        }
        $_arr = is_object($obj) ? get_object_vars($obj) : $obj;
        $arr = array();
        foreach ($_arr as $key => $value) {
            $value = (is_array($value)) || is_object($value) ? $this->objectToArray($value) : $value;
            $arr[$key] = $value;
        }
        return $arr;
    }

    /**
     * Create HttpClient and send request
     *
     * @param string $httpMethod
     *          The Http request method
     *
     * @param array $varArgs
     *          The extra arguments
     *
     * @param string $requestPath
     *          The Http request uri
     *
     * @return mixed The Http response and headers.
     */

    private function sendRequest($httpMethod, array $varArgs, $requestPath = '/')
    {
        $defaultArgs = array(
            'config' => array(),
            'body' => null,
            'headers' => array(),
            'params' => array(),
        );

        $args = array_merge($defaultArgs, $varArgs);
        if (empty($args['config'])) {
            $config = $this->config;
        } else {
            $config = array_merge(
                array(),
                $this->config,
                $args['config']
            );
        }
        if (!isset($args['headers'][HttpHeaders::CONTENT_TYPE])) {
            $args['headers'][HttpHeaders::CONTENT_TYPE] = HttpContentTypes::JSON;
        }
        $path = $this->prefix . $requestPath;
        $response = $this->httpClient->sendRequest(
            $config,
            $httpMethod,
            $path,
            $args['body'],
            $args['headers'],
            $args['params'],
            $this->signer
        );

        $result = $this->parseJsonResult($response['body']);

        return $result;
    }

    /**
     * The method to generate a default Billing which is Postpaid.
     *
     * @return Billing object with Postpaid PaymentTiming.
     */
    private function generateDefaultBilling()
    {
        return new Billing('Postpaid', 'ByBandwidth');
    }

    /**
     * The default method to generate the random String for clientToken if the optional parameter clientToken
     * is not specified by the user.
     *
     * The default algorithm is Mersenne Twister to generate a random UUID,
     * @return String An random String generated by Mersenne Twister.
     */
    public static function generateClientToken()
    {
        $uuid = md5(uniqid(mt_rand(), true));
        return $uuid;
    }
}