<?php
/*
* Copyright 2018 Baidu, Inc.
*
* Licensed under the Apache License, Version 2.0 (the "License"); you may not
* use this file except in compliance with the License. You may obtain a copy of
* the License at
*
* Http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
* WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
* License for the specific language governing permissions and limitations under
* the License.
*/


namespace BaiduBce\Services\EipGroup;

use BaiduBce\Auth\BceV1Signer;
use BaiduBce\BceBaseClient;
use BaiduBce\Http\BceHttpClient;
use BaiduBce\Http\HttpHeaders;
use BaiduBce\Http\HttpMethod;
use BaiduBce\Http\HttpContentTypes;
use BaiduBce\Services\EipGroup\model\Billing;

/**
 * This module provides a client class for EipGroupClient.
 */
class EipGroupClient extends BceBaseClient
{

    private $signer;
    private $httpClient;
    private $prefix = '/v1';

    /**
     * The EipGroupClient constructor.
     *
     * @param array $config The client configuration
     */
    function __construct(array $config)
    {
        parent::__construct($config, 'eipgroup');
        $this->signer = new BceV1Signer();
        $this->httpClient = new BceHttpClient();
    }

    /**
     * Create an EipGroup with the specified options.
     *
     * @param int $bandwidthInMbps
     *          specify the bandwidth in Mbps
     *
     * @param int eipCount
     *          specify the eip count in EipGroup
     *
     * @param string $name
     *          name of EipGroup. The optional parameter
     *
     * @param Billing $billing
     *          billing information. The optional parameter, default paymentTiming is Postpaid
     *
     * @param string $clientToken
     *          if the clientToken is not specified by the user, a random String
     *          generated by default algorithm will be used.
     *
     * @param array $options
     *          The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating EipGroupClient instance.
     *
     * @return mixed
     */
    public function createEipGroup($bandwidthInMbps, $eipCount, $billing, $name = null, $clientToken = null, $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        $body = array();
        if (empty($bandwidthInMbps)) {
            throw new \InvalidArgumentException(
                'request $bandwidthInMbps  should not be empty .'
            );
        }
        if (empty($eipCount)) {
            throw new \InvalidArgumentException(
                'request $eipCount  should not be empty .'
            );
        }
        if (empty($billing)) {
            throw new \InvalidArgumentException(
                'request $billing  should not be empty .'
            );
        }
        $body['name'] = $name;
        $body['eipCount'] = $eipCount;
        $body['bandwidthInMbps'] = $bandwidthInMbps;
        $body['billing'] = $this->objectToArray($billing);
        $params = array();
        if (empty($clientToken)) {
            $params['clientToken'] = $this->generateClientToken();
        } else {
            $params['clientToken'] = $clientToken;
        }
        return $this->sendRequest(
            HttpMethod::POST,
            array(
                'config' => $config,
                'body' => json_encode($body),
                'params' => $params,
            ),
            '/eipgroup'
        );
    }

    /**
     * Resizing EipGroup
     *
     * @param string id
     *          EipGroup's id to be resized
     *
     * @param int bandwidthInMbps
     *          specify new bandwidth in Mbps for EipGroup
     *
     * @param string $clientToken
     *          if the clientToken is not specified by the user, a random String
     *          generated by default algorithm will be used.
     *
     * @param array $options
     *          The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating EipGroupClient instance.
     *
     * @return mixed
     */
    public function resizeEipGroupForBandWidth($id, $bandwidthInMbps, $clientToken = null, $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        $body = array();
        $params = array();
        if (empty($clientToken)) {
            $params['clientToken'] = $this->generateClientToken();
        } else {
            $params['clientToken'] = $clientToken;
        }
        if (empty($id)) {
            throw new \InvalidArgumentException(
                'request $id  should not be empty .'
            );
        }
        if (empty($bandwidthInMbps)) {
            throw new \InvalidArgumentException(
                'request $bandwidthInMbps  should not be empty .'
            );
        }
        $body['bandwidthInMbps'] = $bandwidthInMbps;

        $params['resize'] = null;

        return $this->sendRequest(
            HttpMethod::PUT,
            array(
                'config' => $config,
                'params' => $params,
                'body' => json_encode($body),
            ),
            '/eipgroup/' . $id
        );
    }

    /**
     * Resizing EipGroup
     *
     * @param string id
     *          EipGroup's id to be resized
     *
     * @param int eipAddCount
     *          specify the added counts for EipGroup.The eipAddCount must greater than 0.
     *
     * @param string $clientToken
     *          if the clientToken is not specified by the user, a random String
     *          generated by default algorithm will be used.
     *
     * @param array $options
     *          The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating EipGroupClient instance.
     *
     * @return mixed
     */
    public function resizeEipGroupForEipCount($id, $eipAddCount, $clientToken = null, $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        $body = array();
        $params = array();
        if (empty($id)) {
            throw new \InvalidArgumentException(
                'request $id  should not be empty .'
            );
        }
        if (empty($eipAddCount)) {
            throw new \InvalidArgumentException(
                'request $eipAddCount  should not be empty .'
            );
        }
        if (empty($clientToken)) {
            $params['clientToken'] = $this->generateClientToken();
        } else {
            $params['clientToken'] = $clientToken;
        }
        $body['eipAddCount'] = $eipAddCount;
        $params['resize'] = null;

        return $this->sendRequest(
            HttpMethod::PUT,
            array(
                'config' => $config,
                'params' => $params,
                'body' => json_encode($body),
            ),
            '/eipgroup/' . $id
        );
    }


    /**
     * update EipGroup
     *
     * @param string $id
     *          EipGroup's id to be updated
     *
     * @param string $name
     *          specify the new name EipGroup.
     *
     * @param string $clientToken
     *          if the clientToken is not specified by the user, a random String
     *          generated by default algorithm will be used.
     *
     * @param array $options
     *          The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating EipGroupClient instance.
     *
     * @return mixed
     */
    public function updateEipGroup($id, $name, $clientToken = null, $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        $params = array();
        $body = array();
        if (empty($clientToken)) {
            $params['clientToken'] = $this->generateClientToken();
        } else {
            $params['clientToken'] = $clientToken;
        }
        if (empty($id)) {
            throw new \InvalidArgumentException(
                'request $id  should not be empty .'
            );
        }
        if (empty($name)) {
            throw new \InvalidArgumentException(
                'request $name  should not be empty .'
            );
        }
        $params['update'] = null;
        $body['name'] = $name;

        return $this->sendRequest(
            HttpMethod::PUT,
            array(
                'config' => $config,
                'body' => json_encode($body),
                'params' => $params,
            ),
            '/eipgroup/' . $id
        );
    }

    /**
     * PurchaseReserved EipGroup with fixed duration
     *
     * @param string $id
     *          EipGroup's id to be renewed
     *
     * @param Billing $billing
     *          billing information.
     *
     * @param string $clientToken
     *          if the clientToken is not specified by the user, a random String
     *          generated by default algorithm will be used.
     *
     * @param array $options
     *          The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating EipGroupClient instance.
     *
     * @return mixed
     */
    public function purchaseReservedEipGroup($id, $billing, $clientToken = null, $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        $body = array();
        $params = array();
        if (empty($id)) {
            throw new \InvalidArgumentException(
                'request $id  should not be empty .'
            );
        }
        if (empty($billing)) {
            throw new \InvalidArgumentException(
                'request $billing  should not be empty .'
            );
        } else {
            $reservation = array();
            $reservation['reservationTimeUnit'] = $billing->reservation->reservationTimeUnit;
            $reservation['reservationLength'] = $billing->reservation->reservationLength;
            $billingBody = array();
            $billingBody['reservation'] = $reservation;
            $body['billing'] = $billingBody;
        }
        if (empty($clientToken)) {
            $clientToken = $this->generateClientToken();
        }
        $params['purchaseReserved'] = null;
        $params['clientToken'] = $clientToken;

        return $this->sendRequest(
            HttpMethod::PUT,
            array(
                'config' => $config,
                'params' => $params,
                'body' => json_encode($body),
            ),
            '/eipgroup/' . $id
        );
    }


    /**
     * get a list of EipGroup owned by the authenticated user and specified conditions.
     * we can Also get a single EipGroup function  through this interface by EipGroup condition
     *
     * @param string $id
     *          EipGroup's id condition
     *
     * @param string $name
     *          EipGroup name condition
     *
     * @param string $status
     *          EipGroup instance status condition
     *
     * @param string $marker
     *          The optional parameter marker specified in the original request to specify
     *          where in the results to begin listing.
     *
     * @param int $maxKeys
     *          The optional parameter to specifies the max number of list result to return.
     *          The default value is 1000.
     *
     * @param array $options
     *           The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating EipGroupClient instance.
     *
     * @return mixed
     */
    public function listEipGroups($id = null, $name = null, $status = null, $marker = null, $maxKeys = 1000,
                                  $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        $params = array();
        if ($id !== null) {
            $params['id'] = $id;
        }
        if ($name !== null) {
            $params['name'] = $name;
        }
        if ($status !== null) {
            $params['status'] = $status;
        }
        if ($marker !== null) {
            $params['marker'] = $marker;
        }
        if ($maxKeys !== null) {
            $params['maxKeys'] = $maxKeys;
        }

        return $this->sendRequest(
            HttpMethod::GET,
            array(
                'config' => $config,
                'params' => $params,
            ),
            '/eipgroup'
        );
    }

    /**
     * get a detail of the EipGroup which you specified  .
     *
     * @param string $id
     *          EipGroup's id condition
     *
     * @param array $options
     *           The optional bce configuration, which will overwrite the
     *          default configuration that was passed while creating EipGroupClient instance.
     *
     * @return mixed
     */
    public function getEipGroup($id, $options = array())
    {
        list($config) = $this->parseOptions($options, 'config');
        $params = array();
        if (empty($id)) {
            throw new \InvalidArgumentException(
                'request $id  should not be empty .'
            );
        }
        $params['id'] = $id;
        return $this->sendRequest(
            HttpMethod::GET,
            array(
                'config' => $config,
                'params' => $params,
            ),
            '/eipgroup'
        );
    }


    /**
     * convert object to array
     *
     * @param object $obj
     *
     * @return array
     */
    function objectToArray($obj)
    {
        if (is_array($obj)) {
            return $obj;
        }
        $_arr = is_object($obj) ? get_object_vars($obj) : $obj;
        $arr = array();
        foreach ($_arr as $key => $value) {
            $value = (is_array($value)) || is_object($value) ? $this->objectToArray($value) : $value;
            $arr[$key] = $value;
        }
        return $arr;
    }

    /**
     * Create HttpClient and send request
     *
     * @param string $httpMethod
     *          The Http request method
     *
     * @param array $varArgs
     *          The extra arguments
     *
     * @param string $requestPath
     *          The Http request uri
     *
     * @return mixed The Http response and headers.
     */

    private function sendRequest($httpMethod, array $varArgs, $requestPath = '/')
    {
        $defaultArgs = array(
            'config' => array(),
            'body' => null,
            'headers' => array(),
            'params' => array(),
        );

        $args = array_merge($defaultArgs, $varArgs);
        if (empty($args['config'])) {
            $config = $this->config;
        } else {
            $config = array_merge(
                array(),
                $this->config,
                $args['config']
            );
        }
        if (!isset($args['headers'][HttpHeaders::CONTENT_TYPE])) {
            $args['headers'][HttpHeaders::CONTENT_TYPE] = HttpContentTypes::JSON;
        }
        $path = $this->prefix . $requestPath;
        $response = $this->httpClient->sendRequest(
            $config,
            $httpMethod,
            $path,
            $args['body'],
            $args['headers'],
            $args['params'],
            $this->signer
        );

        $result = $this->parseJsonResult($response['body']);

        return $result;
    }

    /**
     * The method to generate a default Billing which is Postpaid.
     *
     * @return Billing object with Postpaid PaymentTiming.
     */
    private function generateDefaultBilling()
    {
        return new Billing('Postpaid', 'ByBandwidth');
    }

    /**
     * The default method to generate the random String for clientToken if the optional parameter clientToken
     * is not specified by the user.
     *
     * The default algorithm is Mersenne Twister to generate a random UUID,
     * @return String An random String generated by Mersenne Twister.
     */
    public static function generateClientToken()
    {
        $uuid = md5(uniqid(mt_rand(), true));
        return $uuid;
    }
}